// Reuses the upstream dashboard's compact cards, typography and embedded-page delivery.
// This page consumes only the central summary API, never local dashboard event content.
export const styles = `
:root{color-scheme:light;--bg:#f5f7fa;--surface:#fff;--border:#dce2e9;--text:#182434;--muted:#596779;--blue:#235acc}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.6 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}
main{max-width:1160px;margin:auto;padding:32px 24px}header{display:flex;gap:20px;align-items:center;justify-content:space-between;border-bottom:1px solid var(--border);padding-bottom:20px}
h1{font-size:26px;margin:0}h2{font-size:19px;margin:0 0 12px}.eyebrow{font-size:12px;letter-spacing:2px;color:var(--blue);font-weight:700}.muted{color:var(--muted)}p{margin:8px 0}.badge{font-size:13px;border:1px solid #bacbee;background:#eaf0ff;padding:4px 12px;border-radius:16px}
.panel{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:20px;margin-top:20px}.filters{display:flex;flex-wrap:wrap;gap:12px;align-items:end}label{display:grid;gap:5px;min-width:140px;flex:1}input,select,button{font:inherit;padding:9px 12px;border-radius:6px;border:1px solid #b6c3d2;min-width:0;max-width:100%}input,select{background:#fff;color:var(--text)}button{cursor:pointer;background:var(--blue);border-color:var(--blue);color:white}button.secondary{background:transparent;color:var(--blue)}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #8cb2ff;outline-offset:2px}
.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:20px}.metric{padding:18px;background:#fff;border:1px solid var(--border);border-radius:10px}.metric b{display:block;font-size:28px;line-height:1.4}.metric small{color:var(--muted)}.tables{display:grid;grid-template-columns:1fr 1fr;gap:20px}.tables .panel{min-width:0}table{width:100%;border-collapse:collapse;font-size:14px;table-layout:fixed}th,td{text-align:left;padding:10px 4px;border-bottom:1px solid #e7ebf0;overflow-wrap:anywhere}th{color:var(--muted);font-weight:500}td:not(:first-child),th:not(:first-child){text-align:right}.error{color:#a52823;background:#fff1ef;padding:12px;border-radius:6px}.empty{text-align:center;padding:32px;color:var(--muted)}[hidden]{display:none!important}.login{max-width:460px;margin:10vh auto}.login label{margin-top:16px}.login button{margin-top:20px;width:100%}.login form{margin-top:20px}.note{font-size:13px;color:var(--muted)}.day{display:grid;grid-template-columns:100px 1fr 80px;gap:12px;align-items:center;margin:10px 0;font-size:13px}.bar{height:9px;border-radius:6px;background:#dce8ff;overflow:hidden}.bar i{display:block;height:100%;background:var(--blue)}
@media(max-width:680px){main{padding:18px 14px}header{align-items:start}h1{font-size:22px}.metrics{grid-template-columns:repeat(2,1fr)}.metric{padding:14px}.metric b{font-size:23px}.tables{grid-template-columns:1fr;gap:0}.panel{padding:16px}.filters label{min-width:calc(50% - 12px)}.filters button{width:100%}.badge{display:inline-block;white-space:nowrap}header>div:last-child{text-align:right}.day{grid-template-columns:90px 1fr 55px;gap:8px}}
`;
function page(body: string, nonce: string, script = '') {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TeamAI 团队用量</title><style nonce="${nonce}">${styles}</style></head><body>${body}${script ? `<script nonce="${nonce}">${script}</script>` : ''}</body></html>`;
}
export function loginHtml(nonce: string, invalid = false) {
  return page(`<main class="login"><div class="eyebrow">TEAMAI · 团队用量</div><h1>管理员登录</h1><p class="muted">使用管理员身份与访问凭据查看团队汇总。</p>${invalid ? '<p class="error" role="alert">登录失败。请检查身份、凭据及有效期。</p>' : ''}<form method="post" action="/login"><label>管理员标识<input name="id" required maxlength="64" autocomplete="username"></label><label>访问凭据<input name="token" type="password" required maxlength="43" autocomplete="current-password"></label><button>登录</button></form><p class="note">成员上报凭据不能访问管理页面。请通过可信入口获取管理员凭据。</p></main>`, nonce);
}
export function dashboardHtml(nonce: string) {
  return page(`<main><header><div><div class="eyebrow">TEAMAI · 团队用量</div><h1>团队用量总览</h1><p class="muted">按成员、项目与会话归属日期查看已接收统计</p></div><div><span id="dataset" class="badge">加载中</span><form method="post" action="/logout"><button class="secondary">退出登录</button></form></div></header>
<section class="panel"><form id="filters" class="filters"><label>成员<select id="member"><option value="">全部成员</option></select></label><label>项目<select id="project"><option value="">全部项目</option></select></label><label>开始日期（UTC）<input id="from" type="date" required></label><label>结束日期（UTC）<input id="to" type="date" required></label><button>查询统计</button></form><p id="status" class="note" aria-live="polite">正在读取统计…</p><p id="error" class="error" role="alert" hidden></p></section>
<div id="results" hidden><section id="metrics" class="metrics" aria-label="用量指标"></section><p id="empty" class="panel empty" hidden>此筛选范围暂无上报。真实成员尚未接入时，这里会保持为空。</p><div class="tables"><section class="panel"><h2>成员汇总</h2><div id="members"></div></section><section class="panel"><h2>项目汇总</h2><div id="projects"></div></section></div><section class="panel"><h2>每日会话用量</h2><p class="note">按会话首次统计日归属；展示已知 token，部分未知会单独标出。</p><div id="days"></div></section></div>
<section class="panel note"><h2>计量说明</h2><p>输入、输出、缓存读取、缓存写入沿用 TeamAI 的独立分桶。未知值不按零处理；汇总含未知时显示“已知部分”。</p><p>时间为 UTC。会话累计快照归属首次统计日，跨日续接仍更新该日；这不是所选期间内逐请求消耗。相同事件重试和旧序号上报不会重复累计。</p><p>此处展示客户端已上报统计，不是 OpenAI 官方账单、订阅席位费用或账号剩余配额。默认不接收提示词、回复、工具参数、文件路径或历史会话。</p></section></main>`, nonce, `
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('zh-CN').format(n);
const total=row=>Object.values(row.tokens).reduce((a,b)=>a+b,0),unknown=row=>Object.values(row.unknown).some(n=>n>0);
const totalText=row=>Object.values(row.unknown).every(n=>n===row.sessions)&&row.sessions>0?'\u672a\u77e5':fmt(total(row))+(unknown(row)?' *':'');
function node(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n}
function measured(value,missing,sessions){return missing===sessions&&sessions>0?'未知':fmt(value)+(missing?'（已知部分）':'')}
function table(id,rows){const box=$(id);box.replaceChildren();if(!rows.length){box.append(node('p','暂无数据'));return}const t=node('table'),head=node('tr');for(const x of ['标识','会话','Token'])head.append(node('th',x));t.append(head);for(const row of rows){const tr=node('tr');tr.append(node('td',row.id),node('td',fmt(row.sessions)),node('td',totalText(row)));t.append(tr)}box.append(t);if(rows.some(unknown))box.append(node('p','* 含未知分桶，数值仅为已知部分'))}
function metrics(s){$('metrics').replaceChildren();for(const [label,value,detail] of [['会话数',fmt(s.sessions),'已接收的匿名会话'],['对话轮数',measured(s.prompts,s.unknownPrompts,s.sessions),'客户端累计统计'],['输入 Token',measured(s.tokens.input,s.unknown.input,s.sessions),'不含缓存桶'],['输出 Token',measured(s.tokens.output,s.unknown.output,s.sessions),'已测得的输出'],['缓存读取 Token',measured(s.tokens.cacheRead,s.unknown.cacheRead,s.sessions),'缓存命中的输入'],['缓存写入 Token',measured(s.tokens.cacheCreation,s.unknown.cacheCreation,s.sessions),'未知写入不估算']]){const card=node('div');card.className='metric';card.append(node('span',label),node('b',value),node('small',detail));$('metrics').append(card)}}
async function request(url){const r=await fetch(url);if(r.status===401){location.href='/login';throw Error('登录已失效，请重新登录。')}if(!r.ok)throw Error(r.status===400?'筛选日期或条件无效，请检查后重试。':'统计暂时无法读取，请稍后重试。');return r.json()}
async function load(){ $('error').hidden=true;$('results').hidden=true;$('status').textContent='正在读取统计…';try{const q=new URLSearchParams();for(const key of ['member','project','from','to'])if($(key).value)q.set(key,$(key).value);const s=await request('/api/usage/summary?'+q);$('dataset').textContent=s.dataset==='synthetic'?'合成验证数据':'已上报数据';metrics(s);table('members',s.members);table('projects',s.projects);$('days').replaceChildren();const max=Math.max(1,...s.days.map(total));for(const day of s.days){const row=node('div');row.className='day';const bar=node('div');bar.className='bar';const fill=node('i');fill.style.width=(100*total(day)/max)+'%';bar.append(fill);row.append(node('span',day.id),bar,node('span',totalText(day)));$('days').append(row)}$('empty').hidden=s.sessions!==0;$('status').textContent='最后接受的新快照：'+(s.latestReport||'尚无上报')+' · UTC';$('results').hidden=false}catch(e){$('error').textContent=e.message;$('error').hidden=false;$('status').textContent='读取失败，尚未更新结果。'}}
$('filters').addEventListener('submit',e=>{e.preventDefault();load()});
(async()=>{try{const o=await request('/api/usage/options');for(const [id,values] of [['member',o.members],['project',o.projects]])for(const value of values){const option=node('option',value);option.value=value;$(id).append(option)}const now=new Date();$('to').value=now.toISOString().slice(0,10);$('from').value=new Date(now.getTime()-29*86400000).toISOString().slice(0,10);await load()}catch(e){$('error').textContent=e.message;$('error').hidden=false}})();
`);
}
